language: node_js
node_js: stable

# S: Build Lifecycle
install:
    - npm install

#before_script:
# - npm install -g gulp

script:
    - hexo clean
  - hexo generate

after_script:
    - cd ./public
    - git init
    - git config user.name "${name}"
    - git config user.email "${email}"
    - git add .
    - git commit -m "Update docs"
    - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
    only:
        - blog-resource
env:
    global:
        - GH_REF: github.com/YaliixxG/YaliixxG.github.io.git
